# -*- coding: utf-8 -*-
"""Tnq_EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19VPMgdopQX8an5vbiY7OYa_mOp2LTMMY

IMPORTING THE PACKAGES
"""

import pandas as pd
import numpy as np

"""READ THE FILE"""

df=pd.read_csv("/content/world_population.csv")

df.head()

df.tail()

"""DATA PREPROCESSING"""

df.info()

df.shape

df.columns

df.corr()

df.describe()

df.sum().isna()

df.dtypes

"""CONVERTING ALL THE OBJECTS INTO INTEGERS"""

# Import label encoder
from sklearn import preprocessing

# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'Product Type'.
df['CCA3']= label_encoder.fit_transform(df['CCA3'])
df['CCA3'].unique()

df['Country']= label_encoder.fit_transform(df['Country'])
df['Country'].unique()

df['Capital']= label_encoder.fit_transform(df['Capital'])
df['Capital'].unique()

df['Continent']= label_encoder.fit_transform(df['Continent'])
df['Continent'].unique()

df.dtypes

"""EXPLORATORY DATA ANALYSIS"""

df.columns

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(df['Continent'])
fig = plt.gcf()
fig.set_size_inches(6,6)
plt.title('Continent')

sns.countplot(df['Area (km²)'])
fig = plt.gcf()
fig.set_size_inches(6,6)
plt.title('Area (km²)')

plt.hist(df['Growth Rate'])
fig = plt.gcf()
fig.set_size_inches(5,5)
plt.title('Growth Rate')

plt.hist(df['2015 Population'])
fig = plt.gcf()
fig.set_size_inches(6,6)
plt.title('2015 Population')

df.groupby('Continent').Continent.count().plot(kind='pie')
plt.title('Continent')
plt.show()

plt.scatter(x='Area (km²)', y='Continent')
plt.show()

sns.heatmap(df.corr(),annot=True,cmap='YlGnBu')

df.hist(xrot = 20,figsize = (15,15),color = "Blue")
plt.show()

